### PR TITLE
Mention CS-SI/tuleap-jenkins-lib library to configure feedbacks on PR

### PR DESCRIPTION
**Pull request by LeSuisse**
It makes things easier to configure especially in a pipeline.

### CODE REVIEW

**Comment by LeSuisse** [comment]
Waiting on CS-SI/tuleap-jenkins-lib#1 to mark it ready for review.

**Comment by LeSuisse** [comment]
This is now ready for review, can an integrator review this please?

**Comment by Erwyn** [comment]
Good for me, will merge once this is rebased.

**Comment by LeSuisse** [comment]
> Please rebase

I would have appreciated a merge/review of the PR (requested since 7 days) before updating the structure of the user guide.

**Pull request merged**
